  import Head from "next/head";
  import Image from "next/image";
  import styles from "../styles/Home.module.css";
  import { useEffect } from "react";
  import { useRouter } from "next/router";
  export async function getServerSideProps({ query }) {
    const page = query.page ? query.page : 1; // Get the page number from query parameters or set it to 1 by default.
    const res = await fetch(
      `https://rickandmortyapi.com/api/character?page=${page}`
    );
    const data = await res.json();
    return {
      props: {
        todos: data,
        currentPage: parseInt(page),
      },
    };
  }

  export default function Home({ todos, currentPage }) {
    const router = useRouter();
    const handleNextPage = () => {
      const nextPage = currentPage + 1;
      router.push(`/?page=${nextPage}`);
    };
    const ITEMS_PER_PAGE = 5; // Number of items to show per page

    // Calculate the total number of pages
    const totalPageCount = todos.info?.pages || 0;
  
    // Calculate the start and end page numbers for the pagination
    let startPage = currentPage - Math.floor(ITEMS_PER_PAGE / 2);
    if (startPage < 1) {
      startPage = 1;
    }
    let endPage = startPage + ITEMS_PER_PAGE - 1;
    if (endPage > totalPageCount) {
      endPage = totalPageCount;
      startPage = endPage - ITEMS_PER_PAGE + 1;
      if (startPage < 1) {
        startPage = 1;
      }
    }
    const handlePageNavigation = (pageNumber) => {
      router.push(`/?page=${pageNumber}`);
    };
  
    // Function to handle previous page navigation
    const handlePreviousPage = () => {
      const previousPage = currentPage - 1;
      router.push(`/?page=${previousPage}`);
    };

    // Ensure that if the current page is greater than the last page, the user gets redirected to the last page.
    useEffect(() => {
      if (todos.info && currentPage > todos.info.pages) {
        router.push(`/?page=${todos.info.pages}`);
      }
    }, [currentPage, todos.info, router]);
    return (
      <div className="bg-black selection:bg-fuchsia-300 selection:text-fuchsia-900">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container bg-black  mx-auto shadow-xl text-center">
          <h1
            className="font-bold text-[2rem] pt-1  lg:text-[4rem] bg-black lg:pb-3 pb-1
          text-pink-500 "
          >
            Data Fetched On Server Side With NextJS
          </h1>
          <div className="bg-black   ">
            {todos &&
              todos.results.map((items, index) => (
                <div
                  className="md:flex shadow-alligator mx-auto max-w-xs md:max-w-2xl lg:max-w-3xl   rounded-3xl  mt-5 md:mt-12 bg-gray-900 md:bg-gray-950 "
                  key={index}
                >
                  <div className="">
                    <img
                      className="md:rounded-l-3xl md:rounded-tr-none w-full h-full rounded-t-3xl  object-cover"
                      src={items.image}
                      alt=""
                    />
                  </div>
                  <div className="md:pl-10 text-center pb-8 pt-5   md:pb-5 md:text-start">
                    <h3 className="text-white  md:pt-0  hover:text-violet-300 hover:ease-in-out duration-200 cursor-pointer   font-bold text-3xl">
                      {items.name}
                    </h3>
                    <h6 className="text-white font-semibold  text-2xl mt-3">
                      Status :{" "}
                      <span
                        className={`${
                          items.status === "Alive"
                            ? "text-green-500"
                            : "text-red-600"
                        }`}
                      >
                        {items.status}
                      </span>
                    </h6>
                    <h6 className="text-white mt-3  font-semibold text-2xl">
                      Gender:{" "}
                      <span
                        className={`${
                          items.gender === "Male"
                            ? "text-pink-500"
                            : items.gender === "Female"
                            ? "text-sky-500"
                            : "text-gray-300"
                        }`}
                      >
                        {items.gender}
                      </span>
                    </h6>
                    <h6 className="text-white mt-3  font-semibold text-2xl">
                      Species:{" "}
                      <span
                        className={`${
                          items.species === "Alien"
                            ? "text-green-600"
                            : "text-yellow-400"
                        }`}
                      >
                        {items.species}
                      </span>
                    </h6>
                    <h6 className="text-white text-xl font-semibold mt-2 ">
                      Type:{" "}
                      <span className={`${items.type?"text-fuchsia-600":"text-stone-700"}  hover:ease-in-out duration-200 hover:text-orange-500 `}>
                        {" "}
                        {items.type || "unknown"}
                      </span>
                    </h6>
                    <p className="text-white  font-semibold text-xl mt-2 ">
                      Last Known Location:{" "}
                      <span className={`${items.location.name === "unknown" ? "text-stone-700" : "text-teal-400"} hover:ease-in-out duration-200 hover:text-orange-500`}>
                        {items.location.name}
                      </span>
                    </p>
                  </div>
                </div>
              ))}
          </div>
        </div>
        <div className="flex justify-center space-x-2  md:space-x-5 mt-14">
          {currentPage > 1 && (
            <button
              className="bg-pink-500 hover:bg-pink-600 text-white px-4 py-2 rounded"
              onClick={handlePreviousPage}
            >
              Previous
            </button>
          )}
            <div className="text-white font-semibold flex space-x-2">
          {Array.from({ length: endPage - startPage + 1 }, (_, index) => {
            const pageNumber = startPage + index;
            return (
              <button
                key={pageNumber}
                className={`${
                  pageNumber === currentPage
                    ? "bg-pink-600"
                    : "bg-pink-500 hover:bg-pink-600"
                } text-white px-3 py-2 rounded`}
                onClick={() => handlePageNavigation(pageNumber)}
              >
                {pageNumber}
              </button>
            );
          })}
        </div>

          {currentPage < (todos.info && todos.info.pages) && (
            <button
              className="bg-pink-500 hover:bg-pink-600 text-white px-4 py-2 rounded"
              onClick={handleNextPage}
            >
              Next
            </button>
          )}
          
        </div>
        <div className="text-fuchsia-500 mt-5 flex items-center justify-center font-semibold">
          Page {currentPage} of {todos.info && todos.info.pages}
        </div>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by Uday Bhanu❤️
          </a>
        </footer>
      </div>
    );
  }
