import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getServerSideProps(){
  const res=await fetch("https://jsonplaceholder.typicode.com/todos")
  const data =await res.json();
  return {
    props:{
      todos:data
    }
  }
}

export default function Home({todos}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container mx-auto shadow-xl text-center'>
        <h1 className='font-bold text-[2rem] pt-1  lg:text-[4rem] bg-black lg:pb-3 pb-1
         text-pink-500 '>Data Fetched On Server Side With NextJS</h1>

      {todos?.length===0 ?(
        <div className="loading">
          loading
        </div>):(
          todos?.map((todo)=>(
            <div className='lg:text-[1.5rem] text-[1.1rem] truncate pl-2 pr-2 hover:text-pink-400 ease-in duration-300 font-semibold  text-white p-3 lg:p-5 bg-black '  key={todo.id}>
              {todo.id}:{todo.title}
            </div>
          ))
        
      )}
      </div>

     

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by ❤️
         Uday
        </a>
      </footer>
    </div>
  )
}
